### PR TITLE
spontaneous scrolls fix

### LINKED ISSUE #876: Spontaneous Caster Scroll Copy now counts as spells learned on levelup
**Describe the bug**
spontaneous copied scrolls do now count as spells learned on levelup (they did not in a previous version)

**To Reproduce**
- create a sorcerer on lvl1
- learn at least one scroll
- level up to lvl 3
- you should go from 2 to 3 spells known, but this does not happen (log shows 3 of 3 spells known)

**Version Info:**
 - ToyBox Version: cbec49c1

**Additional context**
my guess at why that happens is that `CopiedFromScroll` does not get copied for the levelup and thats why it is always false in `GetActualSpellsLearned`

### PR DESCRIPTION
**Pull request by mcb5637**
close #876

### CODE REVIEW

File: ToyBox/classes/Infrastructure/CasterHelpers.cs [hunk 1]
```diff
@@ -169,10 +170,34 @@ public static class CasterHelpers {
                 .Where(x => x.CharacterClass == spellbook.Blueprint.CharacterClass && (x.Archetype == null || unit.Progression.IsArchetype(x.Archetype))).Select(y => y.Spell)
                 .ToList();
 
-            return GetActualSpellsLearned(spellbook, level, spellsToIgnore);
+            Spellbook real = null;
+            if (unit.TryGetPartyMemberForLevelUpVersion(out var ch))
```
Comment (cabarius) [inline ToyBox/classes/Infrastructure/CasterHelpers.cs:174]: Please adopt the brace on the same line as the if style used by the rest of the project

File: ToyBox/classes/Infrastructure/CasterHelpers.cs [hunk 2]
```diff
@@ -169,10 +170,34 @@ public static class CasterHelpers {
...
+                    if (sp == null)
+                        return true;
+                    return !sp.IsTemporary
+                        && !sp.CopiedFromScroll
+                        && !sp.IsFromMythicSpellList
+                        && sp.SourceItem == null
+                        && sp.SourceItemEquipmentBlueprint == null
+                        && sp.SourceItemUsableBlueprint == null
+                        && !sp.IsMysticTheurgeCombinedSpell;
+                };
```
Comment (cabarius) [inline ToyBox/classes/Infrastructure/CasterHelpers.cs:199]: Remove ;

File: ToyBox/classes/Infrastructure/CasterHelpers.cs [hunk 3]
```diff
@@ -169,10 +170,34 @@ public static class CasterHelpers {
...
+            return GetActualSpellsLearned(spellbook, level, spellsToIgnore, real);
         }
 
-        public static int GetActualSpellsLearned(Spellbook spellbook, int level, List<BlueprintAbility> spellsToIgnore) {
+        public static int GetActualSpellsLearned(Spellbook spellbook, int level, List<BlueprintAbility> spellsToIgnore, Spellbook real = null) {
+            Func<AbilityData, bool> cond = x => true;
+            if (real != null)
+            {
+                var r = real.SureKnownSpells(level);
+                cond = x =>
```
Comment (cabarius) [inline ToyBox/classes/Infrastructure/CasterHelpers.cs:187]: Please choose a meaningful identifier name that describes what the condition (so someone else understands your intention when they debug something in in later)

Comment (cabarius) [reply ToyBox/classes/Infrastructure/CasterHelpers.cs:187]: Probably some comments explaining what this is doing would be helpful

**Comment by cabarius** [comment]
Looks like a reasonable patch.  Please fix style and the identifier and add some comments and it will be great.  Thank you so much for doing this.

**Review by cabarius — APPROVED** [review]
